import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import About from '../components/About'
import Main from '../components/Main'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'
function Home() {
    return(
        <div>
            <Head>
                <title>Amrita Sodhi | Software Developer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.jpg"/>
            </Head>
            <Navbar/>
            <Main/>
            <br/>
            <br/>
            <br/>
            <br/>
            <About/>
            <Skills/>
            <Projects/>
            <Contact/>

        </div>
    ) 
 }
 
 export default Home